services:
  map.solutions:
    build: 
      context: context/streamlit
    volumes:
      - ../map-streamlit:/var/www/map.streamlit:cached
    ports:
      - 80:80
    depends_on:
      - api.solutions
      - redis

  api.solutions:
    build: 
      context: context/fastapi
    volumes:
      - ../map-fastapi:/var/www/map.fastapi:cached
    ports:
      - 81:81

  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379